In [41]:
import pandas as pd
import matplotlib.pyplot as plt

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score
from sklearn.metrics import recall_score, classification_report
from sklearn.metrics import confusion_matrix, roc_auc_score
from sklearn.metrics import roc_curve

In [43]:
df = pd.read_csv("Outputs/hotel_bookings_cleaned.csv")
print("Shape:", df.shape)

Shape: (84889, 36)

In [44]:
df.head(5)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_nights,total_guests,total_revenue,arrival_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,01-07-2015,0,2,0.0,1-July-2015
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,01-07-2015,0,2,0.0,1-July-2015
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,02-07-2015,1,1,75.0,1-July-2015
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,02-07-2015,1,1,75.0,1-July-2015
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.0,0,1,Check-Out,03-07-2015,2,2,196.0,1-July-2015

In [45]:
df.info

<bound method DataFrame.info of               hotel  is_canceled  lead_time  arrival_date_year  \
0      Resort Hotel            0        342               2015
1      Resort Hotel            0        737               2015
2      Resort Hotel            0          7               2015
3      Resort Hotel            0         13               2015
4      Resort Hotel            0         14               2015
...             ...          ...        ...                ...
84884    City Hotel            0         23               2017
84885    City Hotel            0        102               2017
84886    City Hotel            0         34               2017
84887    City Hotel            0        109               2017
84888    City Hotel            0        205               2017

      arrival_date_month  arrival_date_week_number  arrival_date_day_of_month  \
0                   July                        27                          1
1                   July                        27                          1
2                   July                        27                          1
3                   July                        27                          1
4                   July                        27                          1
...                  ...                       ...                        ...
84884             August                        35                         30
84885             August                        35                         31
84886             August                        35                         31
84887             August                        35                         31
84888             August                        35                         29

       stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                            0                     0       2  ...
1                            0                     0       2  ...
2                            0                     1       1  ...
3                            0                     1       1  ...
4                            0                     2       2  ...
...                        ...                   ...     ...  ...
84884                        2                     5       2  ...
84885                        2                     5       3  ...
84886                        2                     5       2  ...
84887                        2                     5       2  ...
84888                        2                     7       2  ...

       customer_type     adr required_car_parking_spaces  \
0          Transient    0.00                           0
1          Transient    0.00                           0
2          Transient   75.00                           0
3          Transient   75.00                           0
4          Transient   98.00                           0
...              ...     ...                         ...
84884      Transient   96.14                           0
84885      Transient  225.43                           0
84886      Transient  157.71                           0
84887      Transient  104.40                           0
84888      Transient  151.20                           0

      total_of_special_requests reservation_status reservation_status_date  \
0                             0          Check-Out              01-07-2015
1                             0          Check-Out              01-07-2015
2                             0          Check-Out              02-07-2015
3                             0          Check-Out              02-07-2015
4                             1          Check-Out              03-07-2015
...                         ...                ...                     ...
84884                         0          Check-Out              06-09-2017
84885                         2          Check-Out              07-09-2017
84886                         4          Check-Out              07-09-2017
84887                         0          Check-Out              07-09-2017
84888                         2          Check-Out              07-09-2017

       total_nights  total_guests  total_revenue    arrival_date
0                 0             2           0.00     1-July-2015
1                 0             2           0.00     1-July-2015
2                 1             1          75.00     1-July-2015
3                 1             1          75.00     1-July-2015
4                 2             2         196.00     1-July-2015
...             ...           ...            ...             ...
84884             7             2         672.98  30-August-2017
84885             7             3        1578.01  31-August-2017
84886             7             2        1103.97  31-August-2017
84887             7             2         730.80  31-August-2017
84888             9             2        1360.80  29-August-2017

[84889 rows x 36 columns]>

In [46]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,total_nights,total_guests,total_revenue
count,84889.000000,84889.000000,84889.000000,84889.000000,84889.000000,84889.000000,84889.00000,84889.000000,84889.000000,84889.000000,...,84889.000000,84889.000000,84889.000000,84889.000000,84889.000000,84889.000000,84889.000000,84889.000000,84889.000000,84889.000000
mean,0.271637,80.150444,2016.199637,26.721907,15.798337,1.001319,2.61313,1.866755,0.117683,0.010472,...,0.268822,78.846258,11.307001,0.768250,101.788429,0.082013,0.693541,3.614449,1.994911,373.848770
std,0.444806,86.460475,0.685912,13.812371,8.842121,1.032651,2.05764,0.627788,0.416169,0.112255,...,0.724677,109.037505,54.687341,10.145598,45.205950,0.278223,0.827720,2.767990,0.768068,334.516873
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,-6.380000,0.000000,0.000000,0.000000,0.000000,-63.800000
25%,0.000000,11.000000,2016.000000,15.000000,8.000000,0.000000,1.00000,2.000000,0.000000,0.000000,...,0.000000,9.000000,0.000000,0.000000,71.100000,0.000000,0.000000,2.000000,2.000000,150.000000
50%,0.000000,49.000000,2016.000000,27.000000,16.000000,1.000000,2.00000,2.000000,0.000000,0.000000,...,0.000000,9.000000,0.000000,0.000000,96.530000,0.000000,0.000000,3.000000,2.000000,291.600000
75%,1.000000,125.000000,2017.000000,37.000000,23.000000,2.000000,3.00000,2.000000,0.000000,0.000000,...,0.000000,195.000000,0.000000,0.000000,130.000000,0.000000,1.000000,5.000000,2.000000,484.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.00000,55.000000,10.000000,10.000000,...,21.000000,535.000000,543.000000,391.000000,227.000000,8.000000,5.000000,69.000000,55.000000,7590.000000

In [47]:
df = df.drop(columns=[
    'reservation_status',
    'reservation_status_date',
    'arrival_date'
])
print("After drop:", df.shape)

After drop: (84889, 33)

In [48]:
le = LabelEncoder()
cat_cols = ['hotel', 'meal', 'country',
            'market_segment', 'distribution_channel',
            'reserved_room_type', 'assigned_room_type',
            'deposit_type', 'customer_type',
            'arrival_date_month']

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

print("Encoding done !")
print(df.dtypes)

Encoding done !
hotel                               int64
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                  int64
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                            int64
babies                              int64
meal                                int64
country                             int64
market_segment                      int64
distribution_channel                int64
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                  int64
assigned_room_type                  int64
booking_changes                     int64
deposit_type                        int64
agent                               int64
company                             int64
days_in_waiting_list                int64
customer_type                       int64
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
total_nights                        int64
total_guests                        int64
total_revenue                     float64
dtype: object

In [49]:
X = df.drop('is_canceled', axis=1)
y = df['is_canceled']

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Cancellation rate:", y.mean())

X shape: (84889, 32)
y shape: (84889,)
Cancellation rate: 0.27163707900905887

In [50]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Train size:", X_train.shape)
print("Test size:", X_test.shape)
print("Train size:", y_train.shape)
print("Test size:", y_test.shape)

Train size: (67911, 32)
Test size: (16978, 32)
Train size: (67911,)
Test size: (16978,)